export const reviews = [
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
  {
    teamId: 0,
    id: 0,
    score: 4,
    comment:
      '따듯하게 느껴지는 공간이에요 :) 평소에 달램 이용해보고 싶었는데 이렇게 같이 달램 생기니까 너무 좋아요! 프로그램이 더 많이 늘어났으면 좋겠어요.',
    createdAt: '2024.01.25',
    Gathering: {
      teamId: 0,
      id: 0,
      type: 'string',
      name: '럽윈즈올',
      dateTime: '2024-09-12T04:11:46.435Z',
      location: 'string',
      image: 'string',
    },
    User: {
      teamId: 0,
      id: 0,
      name: '럽윈즈올',
      image: 'string',
    },
  },
];
